# Generated by Django 5.0.7 on 2024-07-27 04:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("all", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodeltranslation",
            name="content",
        ),
    ]
