# Generated by Django 5.0.7 on 2024-07-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("all", "0002_remove_productmodeltranslation_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
